import { httpRouter } from 'convex/server';
import { httpAction } from './_generated/server';
import { internal } from './_generated/api';
const http=httpRouter();
const equal=async(body:string,signature:string,secret:string)=>{const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(body));const bytes=new Uint8Array(sig);const expected=`sha256=${Array.from(bytes).map(x=>x.toString(16).padStart(2,'0')).join('')}`;if(expected.length!==signature.length)return false;let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^signature.charCodeAt(i);return diff===0};
http.route({path:'/github/webhook',method:'POST',handler:httpAction(async(ctx,req)=>{const body=await req.text();const secret=process.env.GITHUB_WEBHOOK_SECRET;if(!secret||!await equal(body,req.headers.get('x-hub-signature-256')??'',secret))return new Response('Invalid signature',{status:401});const event=req.headers.get('x-github-event'),delivery=req.headers.get('x-github-delivery');if(!delivery)return new Response('Missing delivery',{status:400});let p:any;try{p=JSON.parse(body)}catch{return new Response('Invalid JSON',{status:400})}
  if(event==='installation'||event==='installation_repositories'){
    const installation=p.installation?.id;const added=event==='installation'&&p.action==='created'?p.repositories:event==='installation_repositories'?p.repositories_added:[];const removed=event==='installation'&&p.action==='deleted'?p.repositories:event==='installation_repositories'?p.repositories_removed:[];
    for(const [items,isRemoved] of [[added,false],[removed,true]] as const)for(const r of items??[]){const owner=r.full_name?.split('/')[0]??p.installation?.account?.login;if(installation&&owner&&r.name)await ctx.runMutation(internal.jobs.recordRepository,{installation,owner,repo:r.name,removed:isRemoved})}return new Response('Accepted',{status:202});
  }
  if(p.sender?.type==='Bot'||p.sender?.login===process.env.GITHUB_BOT_LOGIN)return new Response('Ignored');
  const auto=event==='pull_request'&&['opened','reopened','ready_for_review','synchronize'].includes(p.action)&&!p.pull_request?.draft;
  const match=event==='issue_comment'&&p.action==='created'&&p.issue?.pull_request?/^\/openreview\s+(review|deep|explain)(?:\s+([^\n]{1,500}))?\s*$/i.exec(p.comment?.body?.trim()??''):null;
  if(!auto&&!match)return new Response('Ignored');const installation=p.installation?.id,owner=p.repository?.owner?.login,repo=p.repository?.name,number=auto?p.pull_request?.number:p.issue?.number,head=auto?p.pull_request?.head?.sha:'',base=auto?p.pull_request?.base?.sha:'';if(!installation||!owner||!repo||!number||auto&&(!head||!base))return new Response('Invalid payload',{status:400});
  const command=match?.[1]?.toLowerCase(),actor=match?p.sender?.login:undefined,question=match?.[2]?.trim();if(match&&(!actor||command==='explain'&&!question))return new Response('Invalid command',{status:400});
  await ctx.runMutation(internal.jobs.recordRepository,{installation,owner,repo});
  await ctx.runMutation(internal.jobs.intake,{delivery,key:command?`${installation}:${owner}/${repo}:${number}:command:${p.comment.id}`:`${installation}:${owner}/${repo}:${number}:${head}:v2`,installation,owner,repo,number,head,base,command,actor,question});return new Response('Accepted',{status:202});
})});
http.route({path:'/worker/claim',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.claim,{}))})});
http.route({path:'/worker/heartbeat',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.heartbeat,await req.json()))})});
http.route({path:'/worker/finish',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.finish,await req.json()))})});
http.route({path:'/worker/skip',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.skip,await req.json()))})});
http.route({path:'/worker/set-revision',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.setRevision,await req.json()))})});
http.route({path:'/worker/fail',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.fail,await req.json()))})});
http.route({path:'/worker/active',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runQuery(internal.jobs.active,await req.json()))})});
http.route({path:'/worker/recent',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runQuery(internal.jobs.recent,{}))})});
http.route({path:'/worker/latest-success',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runQuery(internal.jobs.latestSuccess,await req.json()))})});
http.route({path:'/worker/reserve',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.reserveJob,await req.json()))})});
http.route({path:'/worker/settle',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.settleJob,await req.json()))})});
http.route({path:'/worker/feedback',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.feedback,await req.json()))})});
http.route({path:'/worker/prune',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.prune,await req.json()))})});
http.route({path:'/worker/delete-installation',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.deleteInstallation,await req.json()))})});
http.route({path:'/worker/repositories',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runQuery(internal.jobs.repositories,{}))})});
http.route({path:'/worker/repository',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runQuery(internal.jobs.repository,await req.json()))})});
http.route({path:'/worker/update-repository',method:'POST',handler:httpAction(async(ctx,req)=>{if(!process.env.WORKER_SECRET||req.headers.get('authorization')!==`Bearer ${process.env.WORKER_SECRET}`)return new Response('Unauthorized',{status:401});return Response.json(await ctx.runMutation(internal.jobs.updateRepository,await req.json()))})});
export default http;
