import { internalMutation,internalQuery } from './_generated/server';
import { v } from 'convex/values';
export const recordRepository=internalMutation({args:{installation:v.number(),owner:v.string(),repo:v.string(),removed:v.optional(v.boolean())},handler:async(ctx,a)=>{const key=`${a.installation}:${a.owner}/${a.repo}`,prior=await ctx.db.query('repositories').withIndex('by_key',q=>q.eq('key',key)).unique();if(a.removed){if(prior)await ctx.db.delete(prior._id);return true}if(!prior)await ctx.db.insert('repositories',{key,installation:a.installation,owner:a.owner,repo:a.repo,enabled:true,reviewLimit:1,monthlyLimit:20,updated:Date.now()});return true}});
export const repositories=internalQuery({args:{},handler:async(ctx)=>ctx.db.query('repositories').take(500)});
export const repository=internalQuery({args:{installation:v.number(),owner:v.string(),repo:v.string()},handler:async(ctx,a)=>ctx.db.query('repositories').withIndex('by_key',q=>q.eq('key',`${a.installation}:${a.owner}/${a.repo}`)).unique()});
export const updateRepository=internalMutation({args:{installation:v.number(),owner:v.string(),repo:v.string(),enabled:v.boolean(),reviewLimit:v.number(),monthlyLimit:v.number()},handler:async(ctx,a)=>{const r=await ctx.db.query('repositories').withIndex('by_key',q=>q.eq('key',`${a.installation}:${a.owner}/${a.repo}`)).unique();if(!r||!Number.isFinite(a.reviewLimit)||!Number.isFinite(a.monthlyLimit)||a.reviewLimit<0||a.reviewLimit>100||a.monthlyLimit<0||a.monthlyLimit>10000)return false;await ctx.db.patch(r._id,{enabled:a.enabled,reviewLimit:a.reviewLimit,monthlyLimit:a.monthlyLimit,updated:Date.now()});return true}});
export const intake=internalMutation({args:{delivery:v.string(),key:v.string(),installation:v.number(),owner:v.string(),repo:v.string(),number:v.number(),head:v.string(),base:v.string(),command:v.optional(v.string()),actor:v.optional(v.string()),question:v.optional(v.string())},handler:async(ctx,a)=>{
  if(await ctx.db.query('deliveries').withIndex('by_delivery',q=>q.eq('delivery',a.delivery)).unique())return false;
  await ctx.db.insert('deliveries',{delivery:a.delivery,created:Date.now()});
  if(await ctx.db.query('jobs').withIndex('by_key',q=>q.eq('key',a.key)).unique())return true;
  const prior=await ctx.db.query('jobs').withIndex('by_pr',q=>q.eq('installation',a.installation).eq('owner',a.owner).eq('repo',a.repo).eq('number',a.number)).collect();
  if(!a.command)for(const j of prior)if(j.status==='queued'&&!j.command)await ctx.db.patch(j._id,{status:'superseded'});
  await ctx.db.insert('jobs',{key:a.key,installation:a.installation,owner:a.owner,repo:a.repo,number:a.number,head:a.head,base:a.base,command:a.command,actor:a.actor,question:a.question,status:'queued',created:Date.now(),fence:0,attempts:0});return true;
}});
export const setRevision=internalMutation({args:{id:v.id('jobs'),fence:v.number(),head:v.string(),base:v.string()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.status!=='running'||j.fence!==a.fence||j.head)return false;await ctx.db.patch(a.id,{head:a.head,base:a.base});return true}});
// Worker secret is checked by the HTTP action. Never expose these functions directly to clients.
export const claim=internalMutation({args:{},handler:async(ctx)=>{const now=Date.now();const jobs=await ctx.db.query('jobs').withIndex('by_status',q=>q.eq('status','queued')).take(10);const expired=await ctx.db.query('jobs').withIndex('by_status',q=>q.eq('status','running')).take(20);const job=[...jobs.filter(x=>x.created<now-3000),...expired.filter(x=>(x.leaseUntil??0)<now&&x.attempts<3)].sort((a,b)=>a.created-b.created)[0];if(!job)return null;const fence=job.fence+1;await ctx.db.patch(job._id,{status:'running',leaseUntil:now+120000,fence,attempts:job.attempts+1});return {...job,fence};}});
export const heartbeat=internalMutation({args:{id:v.id('jobs'),fence:v.number()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.fence!==a.fence||j.status!=='running'||(j.leaseUntil??0)<Date.now()||!(await isLatest(ctx,j)))return false;await ctx.db.patch(a.id,{leaseUntil:Date.now()+120000});return true}});
export const finish=internalMutation({args:{id:v.id('jobs'),fence:v.number(),result:v.string(),summaryId:v.optional(v.number())},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.fence!==a.fence||j.status!=='running'||(j.leaseUntil??0)<Date.now()||!(await isLatest(ctx,j)))return false;await ctx.db.patch(a.id,{status:'complete',result:a.result,summaryId:a.summaryId,leaseUntil:undefined});return true}});
export const skip=internalMutation({args:{id:v.id('jobs'),fence:v.number(),reason:v.string()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.fence!==a.fence||j.status!=='running')return false;await ctx.db.patch(a.id,{status:'superseded',lastError:a.reason.slice(0,300),leaseUntil:undefined});return true}});
export const fail=internalMutation({args:{id:v.id('jobs'),fence:v.number(),message:v.string()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.fence!==a.fence)return false;await ctx.db.patch(a.id,{status:j.attempts>=3?'failed':'queued',lastError:a.message.slice(0,500),leaseUntil:undefined});return true}});
export const reserve=internalMutation({args:{key:v.string(),amount:v.number(),limit:v.number()},handler:async(ctx,a)=>{if(!Number.isFinite(a.amount)||a.amount<0)return false;let b=await ctx.db.query('budgets').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(!b){const id=await ctx.db.insert('budgets',{key:a.key,reserved:0,spent:0});b=(await ctx.db.get(id))!}if(b.reserved+b.spent+a.amount>a.limit)return false;await ctx.db.patch(b._id,{reserved:b.reserved+a.amount});return true}});
export const settle=internalMutation({args:{key:v.string(),reserved:v.number(),actual:v.number()},handler:async(ctx,a)=>{const b=await ctx.db.query('budgets').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(!b)throw Error('No reservation');await ctx.db.patch(b._id,{reserved:Math.max(0,b.reserved-a.reserved),spent:b.spent+a.actual})}});
export const reserveJob=internalMutation({args:{id:v.id('jobs'),fence:v.number(),callKey:v.string(),amount:v.number(),reviewLimit:v.number(),monthlyLimit:v.number()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.fence!==a.fence||j.status!=='running'||(j.leaseUntil??0)<Date.now()||!(await isLatest(ctx,j))||!Number.isFinite(a.amount)||a.amount<0||!Number.isFinite(a.reviewLimit)||!Number.isFinite(a.monthlyLimit))return false;
  if(await ctx.db.query('reservations').withIndex('by_key',q=>q.eq('key',`${j.key}:${a.callKey}`)).unique())return false;
  const month=new Date().toISOString().slice(0,7);const keys=[{key:`review:${j.key}`,limit:a.reviewLimit},{key:`month:${j.installation}:${month}`,limit:a.monthlyLimit}];
  const rows=await Promise.all(keys.map(x=>ctx.db.query('budgets').withIndex('by_key',q=>q.eq('key',x.key)).unique()));if(rows.some((r,i)=>(r?.reserved??0)+(r?.spent??0)+a.amount>keys[i].limit))return false;
  for(let i=0;i<keys.length;i++){const r=rows[i];if(r)await ctx.db.patch(r._id,{reserved:r.reserved+a.amount});else await ctx.db.insert('budgets',{key:keys[i].key,reserved:a.amount,spent:0})}await ctx.db.insert('reservations',{key:`${j.key}:${a.callKey}`,job:j._id,fence:a.fence,month,amount:a.amount,settled:false});return true;
}});
export const settleJob=internalMutation({args:{id:v.id('jobs'),fence:v.number(),callKey:v.string(),actual:v.number()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||!Number.isFinite(a.actual))return false;const r=await ctx.db.query('reservations').withIndex('by_key',q=>q.eq('key',`${j.key}:${a.callKey}`)).unique();if(!r||r.job!==a.id||r.fence!==a.fence)return false;if(r.settled)return true;for(const key of [`review:${j.key}`,`month:${j.installation}:${r.month}`]){const b=await ctx.db.query('budgets').withIndex('by_key',q=>q.eq('key',key)).unique();if(b)await ctx.db.patch(b._id,{reserved:Math.max(0,b.reserved-r.amount),spent:b.spent+Math.max(0,a.actual)})}await ctx.db.patch(r._id,{settled:true});return true}});
export const recent=internalQuery({args:{},handler:async(ctx)=>ctx.db.query('jobs').order('desc').take(100)});
async function isLatest(ctx:any,j:any){if(j.command)return true;const all=await ctx.db.query('jobs').withIndex('by_pr',(q:any)=>q.eq('installation',j.installation).eq('owner',j.owner).eq('repo',j.repo).eq('number',j.number)).collect();return !all.some((x:any)=>!x.command&&x.created>j.created&&x.status!=='superseded')}
export const active=internalQuery({args:{id:v.id('jobs'),fence:v.number()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);return !!j&&j.status==='running'&&j.fence===a.fence&&(j.leaseUntil??0)>Date.now()&&await isLatest(ctx,j)}});
export const latestSuccess=internalQuery({args:{installation:v.number(),owner:v.string(),repo:v.string(),number:v.number()},handler:async(ctx,a)=>{const all=await ctx.db.query('jobs').withIndex('by_pr',q=>q.eq('installation',a.installation).eq('owner',a.owner).eq('repo',a.repo).eq('number',a.number)).collect();return all.filter(x=>x.status==='complete').sort((x,y)=>y.created-x.created)[0]??null}});
export const feedback=internalMutation({args:{id:v.id('jobs'),fingerprint:v.string(),kind:v.union(v.literal('useful'),v.literal('incorrect'),v.literal('already_handled')),user:v.string()},handler:async(ctx,a)=>{const job=await ctx.db.get(a.id);if(!job||!job.result)return false;let findings:any[];try{const r=JSON.parse(job.result);findings=[...(r.findings??[]),...(r.overflow??[])]}catch{return false}if(!findings?.some(f=>f.fingerprint===a.fingerprint))return false;const existing=await ctx.db.query('feedback').withIndex('by_job',q=>q.eq('job',a.id)).collect();if(existing.some(x=>x.user===a.user&&x.fingerprint===a.fingerprint&&x.kind===a.kind))return true;await ctx.db.insert('feedback',{job:a.id,fingerprint:a.fingerprint,kind:a.kind,user:a.user,created:Date.now()});return true}});
export const prune=internalMutation({args:{days:v.number()},handler:async(ctx,a)=>{const cutoff=Date.now()-Math.max(1,Math.min(365,a.days))*86400000;let removed=0;for(const j of await ctx.db.query('jobs').take(100)){if(j.created>=cutoff||['queued','running'].includes(j.status))continue;for(const f of await ctx.db.query('feedback').withIndex('by_job',q=>q.eq('job',j._id)).collect())await ctx.db.delete(f._id);for(const r of await ctx.db.query('reservations').withIndex('by_job',q=>q.eq('job',j._id)).collect())if(r.settled)await ctx.db.delete(r._id);await ctx.db.delete(j._id);removed++}for(const d of await ctx.db.query('deliveries').take(100))if(d.created<cutoff)await ctx.db.delete(d._id);return removed}});
export const deleteInstallation=internalMutation({args:{installation:v.number()},handler:async(ctx,a)=>{let removed=0;const jobs=await ctx.db.query('jobs').filter(q=>q.eq(q.field('installation'),a.installation)).take(100);for(const j of jobs){for(const f of await ctx.db.query('feedback').withIndex('by_job',q=>q.eq('job',j._id)).collect())await ctx.db.delete(f._id);for(const r of await ctx.db.query('reservations').withIndex('by_job',q=>q.eq('job',j._id)).collect())await ctx.db.delete(r._id);const budget=await ctx.db.query('budgets').withIndex('by_key',q=>q.eq('key',`review:${j.key}`)).unique();if(budget)await ctx.db.delete(budget._id);await ctx.db.delete(j._id);removed++}for(const b of await ctx.db.query('budgets').collect())if(b.key.startsWith(`month:${a.installation}:`))await ctx.db.delete(b._id);for(const r of await ctx.db.query('repositories').collect())if(r.installation===a.installation)await ctx.db.delete(r._id);return {removed,more:jobs.length===100}}});
