import { internalMutation,internalQuery } from './_generated/server';
import { v } from 'convex/values';
export const intake=internalMutation({args:{delivery:v.string(),key:v.string(),installation:v.number(),owner:v.string(),repo:v.string(),number:v.number(),head:v.string(),base:v.string()},handler:async(ctx,a)=>{
  if(await ctx.db.query('deliveries').withIndex('by_delivery',q=>q.eq('delivery',a.delivery)).unique())return false;
  await ctx.db.insert('deliveries',{delivery:a.delivery,created:Date.now()});
  if(await ctx.db.query('jobs').withIndex('by_key',q=>q.eq('key',a.key)).unique())return true;
  await ctx.db.insert('jobs',{key:a.key,installation:a.installation,owner:a.owner,repo:a.repo,number:a.number,head:a.head,base:a.base,status:'queued',created:Date.now(),fence:0,attempts:0});return true;
}});
// Worker secret is checked by the HTTP action. Never expose these functions directly to clients.
export const claim=internalMutation({args:{},handler:async(ctx)=>{const now=Date.now();const jobs=await ctx.db.query('jobs').withIndex('by_status',q=>q.eq('status','queued')).take(10);const expired=await ctx.db.query('jobs').withIndex('by_status',q=>q.eq('status','running')).take(20);const job=[...jobs,...expired.filter(x=>(x.leaseUntil??0)<now&&x.attempts<3)].sort((a,b)=>a.created-b.created)[0];if(!job)return null;const fence=job.fence+1;await ctx.db.patch(job._id,{status:'running',leaseUntil:now+120000,fence,attempts:job.attempts+1});return {...job,fence};}});
export const heartbeat=internalMutation({args:{id:v.id('jobs'),fence:v.number()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.fence!==a.fence||j.status!=='running')return false;await ctx.db.patch(a.id,{leaseUntil:Date.now()+120000});return true}});
export const finish=internalMutation({args:{id:v.id('jobs'),fence:v.number(),result:v.string(),summaryId:v.optional(v.number())},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.fence!==a.fence||j.status!=='running'||(j.leaseUntil??0)<Date.now())return false;await ctx.db.patch(a.id,{status:'complete',result:a.result,summaryId:a.summaryId,leaseUntil:undefined});return true}});
export const fail=internalMutation({args:{id:v.id('jobs'),fence:v.number(),message:v.string()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.fence!==a.fence)return false;await ctx.db.patch(a.id,{status:j.attempts>=3?'failed':'queued',lastError:a.message.slice(0,500),leaseUntil:undefined});return true}});
export const reserve=internalMutation({args:{key:v.string(),amount:v.number(),limit:v.number()},handler:async(ctx,a)=>{if(!Number.isFinite(a.amount)||a.amount<0)return false;let b=await ctx.db.query('budgets').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(!b){const id=await ctx.db.insert('budgets',{key:a.key,reserved:0,spent:0});b=(await ctx.db.get(id))!}if(b.reserved+b.spent+a.amount>a.limit)return false;await ctx.db.patch(b._id,{reserved:b.reserved+a.amount});return true}});
export const settle=internalMutation({args:{key:v.string(),reserved:v.number(),actual:v.number()},handler:async(ctx,a)=>{const b=await ctx.db.query('budgets').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(!b)throw Error('No reservation');await ctx.db.patch(b._id,{reserved:Math.max(0,b.reserved-a.reserved),spent:b.spent+a.actual})}});
export const reserveJob=internalMutation({args:{id:v.id('jobs'),fence:v.number(),amount:v.number(),reviewLimit:v.number(),monthlyLimit:v.number()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j||j.fence!==a.fence||j.status!=='running'||(j.leaseUntil??0)<Date.now()||!Number.isFinite(a.amount)||a.amount<0)return false;
  const month=new Date().toISOString().slice(0,7);const keys=[{key:`review:${j.key}`,limit:a.reviewLimit},{key:`month:${j.installation}:${month}`,limit:a.monthlyLimit}];
  const rows=await Promise.all(keys.map(x=>ctx.db.query('budgets').withIndex('by_key',q=>q.eq('key',x.key)).unique()));if(rows.some((r,i)=>(r?.reserved??0)+(r?.spent??0)+a.amount>keys[i].limit))return false;
  for(let i=0;i<keys.length;i++){const r=rows[i];if(r)await ctx.db.patch(r._id,{reserved:r.reserved+a.amount});else await ctx.db.insert('budgets',{key:keys[i].key,reserved:a.amount,spent:0})}return true;
}});
export const settleJob=internalMutation({args:{id:v.id('jobs'),amount:v.number(),actual:v.number()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);if(!j)return;const month=new Date().toISOString().slice(0,7);for(const key of [`review:${j.key}`,`month:${j.installation}:${month}`]){const b=await ctx.db.query('budgets').withIndex('by_key',q=>q.eq('key',key)).unique();if(b)await ctx.db.patch(b._id,{reserved:Math.max(0,b.reserved-a.amount),spent:b.spent+Math.max(0,a.actual)})}}});
export const recent=internalQuery({args:{},handler:async(ctx)=>ctx.db.query('jobs').order('desc').take(100)});
export const active=internalQuery({args:{id:v.id('jobs'),fence:v.number()},handler:async(ctx,a)=>{const j=await ctx.db.get(a.id);return !!j&&j.status==='running'&&j.fence===a.fence&&(j.leaseUntil??0)>Date.now()}});
export const feedback=internalMutation({args:{id:v.id('jobs'),fingerprint:v.string(),kind:v.union(v.literal('useful'),v.literal('incorrect'),v.literal('already_handled')),user:v.string()},handler:async(ctx,a)=>{const job=await ctx.db.get(a.id);if(!job||!job.result)return false;let findings:any[];try{findings=JSON.parse(job.result).findings}catch{return false}if(!findings?.some(f=>f.fingerprint===a.fingerprint))return false;const existing=await ctx.db.query('feedback').withIndex('by_job',q=>q.eq('job',a.id)).collect();if(existing.some(x=>x.user===a.user&&x.fingerprint===a.fingerprint&&x.kind===a.kind))return true;await ctx.db.insert('feedback',{job:a.id,fingerprint:a.fingerprint,kind:a.kind,user:a.user,created:Date.now()});return true}});
