'use client';
import {useEffect,useState} from 'react';
type Finding={fingerprint:string;path:string;line:number;severity:string;title:string;scenario:string;impact:string;evidence:string;remediation:string;type?:string;confidence?:number;ruleId?:string};
type Job={id:string;owner:string;repo:string;number:number;head:string;status:string;created:number;error?:string;review?:{findings:Finding[];overflow?:Finding[];coverage:string[];status:string;summary?:{overview:string;latest?:string};usage:{inputTokens:number;outputTokens:number;estimatedUsd:number|null}}};
type Repository={installation:number;owner:string;repo:string;enabled:boolean;reviewLimit:number;monthlyLimit:number;canAdmin:boolean};
export function Dashboard({name}:{name:string}){
  const [jobs,setJobs]=useState<Job[]>([]),[repos,setRepos]=useState<Repository[]>([]),[feedback,setFeedback]=useState<Record<string,string>>({});
  const [state,setState]=useState<'loading'|'ready'|'error'>('loading'),[selected,setSelected]=useState<string|null>(null),[notice,setNotice]=useState('');
  useEffect(()=>{let alive=true;async function load(){try{const [jr,rr]=await Promise.all([fetch('/api/reviews',{cache:'no-store'}),fetch('/api/repositories',{cache:'no-store'})]);if(!jr.ok||!rr.ok)throw Error();const [items,connected]=await Promise.all([jr.json(),rr.json()]);if(alive){setJobs(items);setRepos(connected);setState('ready')}}catch{if(alive)setState('error')}}load();const id=setInterval(load,15000);return()=>{alive=false;clearInterval(id)}},[]);
  async function sendFeedback(job:string,fingerprint:string,kind:string){const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:job,fingerprint,kind})});if(r.ok&&(await r.json()).saved)setFeedback(x=>({...x,[`${job}:${fingerprint}`]:kind}))}
  async function saveRepository(repo:Repository){const r=await fetch('/api/repositories',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(repo)});setNotice(r.ok&&(await r.json()).saved?`Saved ${repo.owner}/${repo.repo}`:'Could not save repository settings')}
  const edit=(key:string,patch:Partial<Repository>)=>setRepos(rows=>rows.map(r=>`${r.installation}:${r.owner}/${r.repo}`===key?{...r,...patch}:r));
  const active=jobs.find(x=>x.id===selected)??jobs[0],complete=jobs.filter(j=>j.status==='complete').length,findings=jobs.reduce((n,j)=>n+(j.review?.findings.length??0),0);
  return <div className="shell"><aside><div className="side-label">WORKSPACE</div><div className="nav active">◫ <span>Overview</span></div><div className="side-label space">CONNECTED REPOSITORIES</div>{repos.map(r=><div className="repo" key={`${r.installation}:${r.owner}/${r.repo}`}>⌘ <span>{r.owner}/{r.repo}</span></div>)}<div className="side-bottom">Signed in as<br/><strong>{name}</strong></div></aside><section className="content"><div className="eyebrow">OVERVIEW</div><h1>Review activity<span className="accent">.</span></h1><p className="subtitle">Recent reviews from repositories you can access on GitHub.</p>
    <div className="stats"><div><span>Reviews</span><strong>{jobs.length}</strong></div><div><span>Completed</span><strong>{complete}</strong></div><div><span>Findings</span><strong>{findings}</strong></div><div><span>Estimated cost</span><strong>{jobs.some(j=>j.review?.usage.estimatedUsd===null)?'Partial':`$${jobs.reduce((n,j)=>n+(j.review?.usage.estimatedUsd??0),0).toFixed(3)}`}</strong></div></div>
    <div className="section-head"><h2>Connected repositories</h2><span>Server policy overrides repository budgets</span></div>{repos.length?<div className="repo-grid">{repos.map(r=>{const key=`${r.installation}:${r.owner}/${r.repo}`;return <div className="repo-card" key={key}><strong>{r.owner}/{r.repo}</strong><small>Installation {r.installation}</small>{r.canAdmin?<div className="settings"><label><input type="checkbox" checked={r.enabled} onChange={e=>edit(key,{enabled:e.target.checked})}/> Reviews enabled</label><label>Review limit ($)<input type="number" min="0" max="100" step="0.01" value={r.reviewLimit} onChange={e=>edit(key,{reviewLimit:Number(e.target.value)})}/></label><label>Monthly limit ($)<input type="number" min="0" max="10000" step="0.01" value={r.monthlyLimit} onChange={e=>edit(key,{monthlyLimit:Number(e.target.value)})}/></label><button onClick={()=>saveRepository(r)}>Save settings</button></div>:<small>Repository admin access required to edit settings.</small>}</div>})}</div>:<div className="empty">No connected repositories visible. Install the GitHub App on selected repositories.</div>}{notice&&<p role="status" className="coverage">{notice}</p>}
    <div className="section-head"><h2>Pull requests</h2><span>Updates every 15 seconds</span></div>{state==='loading'?<div className="empty">Loading reviews…</div>:state==='error'?<div className="empty">Could not load reviews. Check the dashboard configuration.</div>:jobs.length===0?<div className="empty"><b>No reviews yet</b><p>Open a pull request in an installed repository.</p></div>:<div className="list">{jobs.map(j=><button key={j.id} className={`row ${active?.id===j.id?'chosen':''}`} onClick={()=>setSelected(j.id)}><div><strong>{j.owner}/{j.repo} <span className="muted">#{j.number}</span></strong><small>{j.head.slice(0,8)} · {new Date(j.created).toLocaleString()}</small></div><div className="row-right"><span className={`status ${j.status}`}>{j.status}</span><span className="chev">→</span></div></button>)}</div>}
    {active&&<section className="detail"><div className="section-head"><h2>Review details</h2><a href={`https://github.com/${active.owner}/${active.repo}/pull/${active.number}`} target="_blank" rel="noreferrer">Open on GitHub ↗</a></div>{active.error&&<p className="warning">{active.error}</p>}{active.review?<>{active.review.summary?.overview&&<p className="summary">{active.review.summary.overview}{active.review.summary.latest&&<><br/><small>Latest push: {active.review.summary.latest}</small></>}</p>}<p className="coverage">Coverage: {active.review.status}{active.review.coverage.length?` · ${active.review.coverage.join('; ')}`:''}</p>{active.review.findings.length?[...active.review.findings,...(active.review.overflow??[])].map((f,i)=><article className="finding" key={i}><span className={`severity ${f.severity}`}>{f.severity}</span>{f.type&&<span className="tag">{f.type}</span>}{f.confidence&&<span className="tag">confidence {f.confidence}/5</span>}{f.ruleId&&<span className="tag">rule {f.ruleId}</span>}<h3>{f.title}</h3><code>{f.path}:{f.line}</code><p>{f.impact}</p><small>Trigger: {f.scenario}</small><small>Evidence: {f.evidence}</small><small>Suggested fix: {f.remediation}</small><div className="feedback">{['useful','incorrect','already_handled'].map(kind=><button key={kind} disabled={!!feedback[`${active.id}:${f.fingerprint}`]} onClick={()=>sendFeedback(active.id,f.fingerprint,kind)}>{feedback[`${active.id}:${f.fingerprint}`]===kind?'✓ ':''}{kind.replace('_',' ')}</button>)}</div></article>):<div className="empty">No actionable findings found within the reviewed scope.</div>}<p className="usage">Tokens: {active.review.usage.inputTokens} in · {active.review.usage.outputTokens} out · Estimated: {active.review.usage.estimatedUsd===null?'unknown':`$${active.review.usage.estimatedUsd.toFixed(4)}`}</p></>:<div className="empty">Review {active.status}.</div>}</section>}</section></div>
}
