// Bootstrap wrappers; regenerated by the Convex CLI after deployment setup.
import {httpActionGeneric,internalMutationGeneric,internalQueryGeneric} from 'convex/server';
import type {MutationBuilder,QueryBuilder,HttpActionBuilder} from 'convex/server';
import type {DataModel} from './dataModel.js';
export const internalMutation=internalMutationGeneric as MutationBuilder<DataModel,'internal'>;
export const internalQuery=internalQueryGeneric as QueryBuilder<DataModel,'internal'>;
export const httpAction=httpActionGeneric as HttpActionBuilder;
