import { describe,it,expect } from 'vitest';
import { Config,parseAddedLines,redactSecrets,review,safePath } from '../src/index.js';
describe('review boundaries',()=>{
  it('maps added lines including removals',()=>expect(parseAddedLines('@@ -2,3 +2,4 @@\n old\n-old\n+new\n+another\n tail')).toEqual([3,4]));
  it('maps a changed line beginning with the increment operator',()=>expect(parseAddedLines('+++ b/a.ts\n@@ -1 +1 @@\n-old\n+++value')).toEqual([1]));
  it('rejects traversal',()=>expect(()=>safePath('../secret')).toThrow());
  it('removes common credentials before the model sees source',()=>{const secret='sk-abcdefghijklmnopqrstuvwxyz123456';expect(redactSecrets(`const token = "${secret}"`)).not.toContain(secret)});
  it('rejects invalid diff locations and duplicate findings',async()=>{const f={path:'a.ts',line:2,severity:'high',title:'Validation bypass',scenario:'Any caller sends an empty token',impact:'Private resource is disclosed',evidence:'The new guard accepts empty tokens',remediation:'Reject empty tokens before checking access'};let calls=0;const r=await review([{path:'a.ts',patch:'@@ -1 +1,2 @@\n old\n+new',addedLines:[2],before:'old',after:'new'}],{analyze:async()=>({findings:++calls===1?{findings:[f,{...f,line:9},f]}:{decisions:[{index:0,retain:true,reason:'Introduced by change',observedCode:'new'},{index:1,retain:true,reason:'Introduced by change',observedCode:'new'}]},usage:{inputTokens:10,outputTokens:20,estimatedUsd:0.01}})},Config.parse({}));expect(r.findings).toHaveLength(1);expect(r.rejected).toHaveLength(2);expect(r.usage.estimatedUsd).toBe(0.02)});
  it('rejects fabricated verification excerpts',async()=>{const f={path:'a.ts',line:1,severity:'high',title:'Permission failure',scenario:'Caller supplies an empty token',impact:'Secret leaks to the caller',evidence:'Guard is missing here',remediation:'Validate token first'};let calls=0;const r=await review([{path:'a.ts',patch:'@@ -1 +1 @@\n-old\n+new',addedLines:[1],before:'old',after:'new'}],{analyze:async()=>({findings:++calls===1?{findings:[f]}:{decisions:[{index:0,retain:true,reason:'Looks plausible',observedCode:'nonexistent'}]},usage:{inputTokens:1,outputTokens:1,estimatedUsd:null}})},Config.parse({}));expect(r.findings).toEqual([]);expect(r.rejected[0].reason).toContain('not found')});
});
