import {auth} from '../../../auth';
import {getToken} from 'next-auth/jwt';
async function identity(request:Request){const session=await auth(),jwt=await getToken({req:request as any,secret:process.env.AUTH_SECRET});return session&&typeof jwt?.githubToken==='string'?jwt.githubToken:null}
function service(){const site=process.env.CONVEX_SITE_URL,secret=process.env.WORKER_SECRET;return site&&secret?{site,headers:{authorization:`Bearer ${secret}`,'content-type':'application/json'}}:null}
async function access(token:string,owner:string,repo:string){try{const r=await fetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`,{headers:{authorization:`Bearer ${token}`,accept:'application/vnd.github+json'},cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
export async function GET(request:Request){const token=await identity(request),s=service();if(!token)return Response.json({error:'Unauthorized'},{status:401});if(!s)return Response.json({error:'Service unavailable'},{status:503});const r=await fetch(`${s.site}/worker/repositories`,{method:'POST',headers:s.headers,cache:'no-store'});if(!r.ok)return Response.json({error:'Service unavailable'},{status:502});const rows=await r.json() as any[];const visible=await Promise.all(rows.map(async x=>{const github=await access(token,x.owner,x.repo);return github?{installation:x.installation,owner:x.owner,repo:x.repo,enabled:x.enabled,reviewLimit:x.reviewLimit,monthlyLimit:x.monthlyLimit,canAdmin:github.permissions?.admin===true}:null}));return Response.json(visible.filter(Boolean),{headers:{'cache-control':'private, no-store'}})}
export async function POST(request:Request){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});const token=await identity(request),s=service();if(!token)return Response.json({error:'Unauthorized'},{status:401});if(!s)return Response.json({error:'Service unavailable'},{status:503});let x:any;try{x=await request.json()}catch{return Response.json({error:'Invalid JSON'},{status:400})}
  if(!Number.isSafeInteger(x?.installation)||!Number.isFinite(x.reviewLimit)||x.reviewLimit<0||x.reviewLimit>100||!Number.isFinite(x.monthlyLimit)||x.monthlyLimit<0||x.monthlyLimit>10000||typeof x.enabled!=='boolean'||typeof x.owner!=='string'||typeof x.repo!=='string'||!/^[\w.-]+$/.test(x.owner)||!/^[\w.-]+$/.test(x.repo))return Response.json({error:'Invalid settings'},{status:400});
  const github=await access(token,x.owner,x.repo);if(!github?.permissions?.admin)return Response.json({error:'Repository admin access required'},{status:403});
  const r=await fetch(`${s.site}/worker/update-repository`,{method:'POST',headers:s.headers,body:JSON.stringify({installation:x.installation,owner:x.owner,repo:x.repo,enabled:x.enabled,reviewLimit:x.reviewLimit,monthlyLimit:x.monthlyLimit})});return Response.json({saved:r.ok&&await r.json()});
}
